### ISSUE TITLE
sed: cannot rename /etc/sedv8NZWT: Device or resource busy

### ISSUE THREAD

**Issue by Jacox98** [djmaze/librespot-snapserver#12]
Hello everybody,

I was trying to pull up this container but I am left with the following error and everything stops.

My configuration is as follows:

snapserver:
        user: root
        volumes:
            - '/mnt/dockerData/mopidy/snapcast:/tmp/snapcast'
            - '/mnt/dockerData/mopidy/snapcast/conf/snapserver.conf:/etc/snapserver.conf'
        image: mazzolino/librespot-snapserver
        container_name: snapserver
        environment:
            - DEVICE_NAME=Snapcast
            - USERNAME=xxxxxxxxxxxxxxxxxx
            - PASSWORD=xxxxxxxxxxxxxxxxxx

### snapserver.conf

[stream]
stream = pipe:///tmp/snapcast/snapfifo?name=Snapserver

[http]
doc_root = /usr/share/snapserver/snapweb

Many thanks in advance

**Comment by djmaze** [comment]
So you are trying to mount your own configuration file. This is not how this image was supposed to be used.

Do you really need a custom configuration? I might adjust the image in that case.

Oh, and sorry for the late response!

**Comment by peetipablo** [comment]
A custome configuration would be good, because then we could also define multiple sources instead of only librespot.

**Comment by chiefy** [comment]
Just ran into this exact situation as well, bind-mounting `/etc/snapserver.conf` because I have multiple sources for Snapserver

**Comment by tobulli** [comment]
having the exact same problem. I am using this container on my Unraid server. On every restart it overwrites the snapserver.conf file stream section making it really hard to change it and add custom sources.

**Comment by dalehumby** [comment]
I have the same issue.

I am trying to enable snapweb for volume control. 

My version of `snapserver.conf` has the line `doc_root = /usr/share/snapserver/snapweb` uncommented, whereas the version that is baked into the docker image has that line commented out.

**Comment by djmaze** [comment]
In the latest master version, you can now mount your custom configuration correctly:

https://github.com/djmaze/librespot-snapserver#custom-configuration
