### ISSUE TITLE
Snapserver doesn't start

### ISSUE THREAD

**Issue by Iriamu19** [djmaze/librespot-snapserver#13]
Hi :)

Firstly, I want to say I'm not an advanced user of linux and Docker.

So my problem is that when I launch the command :
`docker run -d --name snapserver --net host -e DEVICE_NAME=Snapcast mazzolino/librespot-snapserver`

I just see the id of the container and nothing more. No logs of the snapserver of librespot.

Do I have to do something more ?

Thank you for your time

**Comment by djmaze** [comment]
Hello @Iriamu19 , the `-d` flag tells docker to run the container in the background. You can use `docker logs -f <ID OF CONTAINER>` to  see the output after it has been started.

**Comment by Iriamu19** [comment]
Ok thank you it's working !
